baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "0xztcc.com"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  

    
[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 1
